name: Update Password

on:
  schedule:
    - cron: '0 0 * * *'  # This runs once per day
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run password generator script
        run: python games/generate_password.py

      - name: Set up Git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git pull origin main  # Pull the latest changes from the remote before pushing
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push changes
        run: |
          git add password.json
          git commit -m "Auto-update password" || echo "No changes to commit"
          git push
