name: Update Password Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:    # Also allow manual trigger

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install -r requirements.txt || true  # (only if you need it)

      - name: Run password generator
        run: python scripts/generate_password.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add password.json
          git commit -m "Auto-update password" || echo "No changes to commit"
          git push
