name: Update Password

on:
  schedule:
    - cron: '0 0 * * *'  # This runs once per day, adjust as needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install random

      - name: Run password generator script
        run: |
          python generate_password.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add password.json
          git commit -m "Auto-update password"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
